language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - chmod +x ./node_modules/karma/bin/karma
  - chmod +x ./node_modules/.bin/gulp

branches:
  only:
    - gh-pages